import { ReactNode } from 'react';

import { NextAuthProvider, ThemeProvider, ToastProvider } from '@/providers';

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Gym Client App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider>
        <body>
          <NextAuthProvider>
            <ToastProvider>{children}</ToastProvider>
          </NextAuthProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
